services:
  traefik:
    image: traefik:v3.7
    command:
      - --api.dashboard=true
      - --providers.docker=true
      - --providers.docker.exposedbydefault=false
      - --entrypoints.web.address=:80
    labels:
      - traefik.enable=true
      # Traefik Dashboard
      - traefik.http.routers.dashboard.rule=Host(`traefik-console.localhost`)
      - traefik.http.routers.dashboard.entrypoints=web
      - traefik.http.routers.dashboard.service=api@internal
    ports:
      - "80:80"
    networks:
      - app
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    restart: unless-stopped

  backend:
    build: .
    environment:
      SPRING_PROFILES_ACTIVE: ${SPRING_PROFILES_ACTIVE:-prod}
      JAVA_TOOL_OPTIONS: ${JAVA_TOOL_OPTIONS:-}
      DATABASE_URL: ${BACKEND_DB_URL}
      DATABASE_USERNAME: ${POSTGRES_USERNAME}
      DATABASE_PASSWORD: ${POSTGRES_PASSWORD}
      S3_INTERNAL_ENDPOINT: ${BACKEND_S3_INTERNAL_ENDPOINT}
      S3_EXTERNAL_ENDPOINT: ${BACKEND_S3_EXTERNAL_ENDPOINT}
      S3_ACCESS_KEY: ${MINIO_ROOT_USERNAME}
      S3_SECRET_KEY: ${MINIO_ROOT_PASSWORD}
      S3_BUCKET: ${BACKEND_S3_BUCKET_NAME}
      JWT_ISSUER_URI: ${BACKEND_JWT_ISSUER_URI}
      JWT_JWK_SET_URI: ${BACKEND_JWT_JWK_SET_URI}
    labels:
      - traefik.enable=true
      # Backend API
      - traefik.http.routers.backend.rule=Host(`api.localhost`)
      - traefik.http.routers.backend.entrypoints=web
      - traefik.http.services.backend.loadbalancer.server.port=8080
    ports:
      - "5005:5005" # IntelliJ IDEA debug port (TCP)
    networks:
      - app
    depends_on:
      postgres:
        condition: service_healthy
      minio:
        condition: service_healthy
      keycloak:
        condition: service_healthy
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8081/actuator/health/readiness" ]
      interval: 5s
      timeout: 3s
      retries: 10
    restart: unless-stopped

  postgres:
    image: 'postgres:18.3-alpine'
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USERNAME}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - ./init/postgres/:/docker-entrypoint-initdb.d/:ro
      - postgres_data:/var/lib/postgresql
    ports:
      - "${POSTGRES_PORT:-5432}:5432" # Port for database client (TCP)
    networks:
      - app
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USERNAME} -d ${POSTGRES_DB}" ]
      interval: 5s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  minio:
    image: 'quay.io/minio/minio:RELEASE.2025-09-07T16-13-09Z'
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USERNAME}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
    command: server /data --console-address ":9001"
    labels:
      - traefik.enable=true
      # MinIO API (S3)
      - traefik.http.routers.minio.rule=Host(`s3.localhost`)
      - traefik.http.routers.minio.entrypoints=web
      - traefik.http.routers.minio.service=minio
      - traefik.http.services.minio.loadbalancer.server.port=9000
      # MinIO Console
      - traefik.http.routers.minio-console.rule=Host(`minio-console.localhost`)
      - traefik.http.routers.minio-console.entrypoints=web
      - traefik.http.routers.minio-console.service=minio-console
      - traefik.http.services.minio-console.loadbalancer.server.port=9001
    volumes:
      - minio_data:/data
    networks:
      - app
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:9000/minio/health/live" ]
      interval: 5s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  keycloak:
    image: 'quay.io/keycloak/keycloak:26.5'
    environment:
      # Base configuration
      KC_BOOTSTRAP_ADMIN_USERNAME: ${KEYCLOAK_BOOTSTRAP_ADMIN_USERNAME}
      KC_BOOTSTRAP_ADMIN_PASSWORD: ${KEYCLOAK_BOOTSTRAP_ADMIN_PASSWORD}
      KC_PROXY_HEADERS: xforwarded
      KC_HEALTH_ENABLED: true
      # Database configuration
      KC_DB_URL: ${KEYCLOAK_DB_URL}
      KC_DB: ${KEYCLOAK_DB}
      KC_DB_USERNAME: ${KEYCLOAK_DB_USERNAME}
      KC_DB_PASSWORD: ${KEYCLOAK_DB_PASSWORD}
    command: start-dev --import-realm
    labels:
      - traefik.enable=true
      # Keycloak Auth & Admin
      - traefik.http.routers.keycloak.rule=Host(`auth.localhost`)
      - traefik.http.routers.keycloak.entrypoints=web
      - traefik.http.services.keycloak.loadbalancer.server.port=8080
    networks:
      - app
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - ./init/keycloak:/opt/keycloak/data/import:ro
      - keycloak_data:/opt/keycloak/data
    healthcheck:
      test: [ "CMD-SHELL", "exec 3<>/dev/tcp/127.0.0.1/9000;echo -e 'GET /health/ready HTTP/1.1\r\nhost: http://localhost\r\nConnection: close\r\n\r\n' >&3;if [ $? -eq 0 ]; then echo 'Healthcheck Successful';exit 0;else echo 'Healthcheck Failed';exit 1;fi;" ]
      interval: 15s
      timeout: 10s
      retries: 5
    restart: unless-stopped

  seed:
    build: ./seed
    depends_on:
      backend:
        condition: service_healthy
    volumes:
      - postgres_data:/postgres
      - minio_data:/minio
    environment:
      # MinIO
      MINIO_HOST: minio:9000
      MINIO_ACCESS_KEY: ${MINIO_ROOT_USERNAME}
      MINIO_SECRET_KEY: ${MINIO_ROOT_PASSWORD}
      MINIO_BUCKET: ${BACKEND_S3_BUCKET_NAME}
      # PostgreSQL
      POSTGRES_PORT: 5432
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USERNAME: ${POSTGRES_USERNAME}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    networks:
      - app
    restart: no

  prometheus:
    image: prom/prometheus:v3.11.3
    depends_on:
      backend:
        condition: service_healthy
    volumes:
      - prometheus_data:/prometheus
      - ./ops/prometheus/prometheus.yaml:/etc/prometheus/prometheus.yml:ro
    labels:
      - traefik.enable=true
      # Prometheus Metrics
      - traefik.http.routers.prometheus.rule=Host(`prometheus.localhost`)
      - traefik.http.routers.prometheus.entrypoints=web
      - traefik.http.services.prometheus.loadbalancer.server.port=9090
    networks:
      - app
    healthcheck:
      test: [ "CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:9090/-/healthy" ]
      interval: 5s
      timeout: 3s
      retries: 5
    restart: unless-stopped

  grafana:
    image: grafana/grafana:13.0
    depends_on:
      prometheus:
        condition: service_healthy
    environment:
      GF_SECURITY_ADMIN_USER: ${GRAFANA_ADMIN_USER}
      GF_SECURITY_ADMIN_PASSWORD: ${GRAFANA_ADMIN_PASSWORD}
    volumes:
      - grafana_data:/var/lib/grafana
      - ./ops/grafana/provisioning:/etc/grafana/provisioning:ro
      - ./ops/grafana/dashboards:/var/lib/grafana/dashboards:ro
    labels:
      - traefik.enable=true
      # Grafana Dashboard
      - traefik.http.routers.grafana.rule=Host(`grafana.localhost`)
      - traefik.http.routers.grafana.entrypoints=web
      - traefik.http.services.grafana.loadbalancer.server.port=3000
    networks:
      - app
    healthcheck:
      test: [ "CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:3000/api/health" ]
      interval: 5s
      timeout: 3s
      retries: 5
    restart: unless-stopped

volumes:
  postgres_data:
  minio_data:
  keycloak_data:
  prometheus_data:
  grafana_data:

networks:
  app:
