spring.application.name=comics
spring.mvc.problem-details.enabled=true
# Actuator
management.endpoints.web.exposure.include=health,info,prometheus,metrics
management.endpoint.health.show-details=always
management.metrics.enable.hikaricp=true
management.prometheus.metrics.export.enabled=true
management.server.port=${MANAGEMENT_SERVER_PORT:8081}
# Liquibase
spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.yaml
spring.liquibase.enabled=true
# Hibernate / JPA
spring.jpa.hibernate.ddl-auto=validate
spring.datasource.driver-class-name=org.postgresql.Driver
spring.data.web.pageable.default-page-size=20
spring.data.web.pageable.max-page-size=40
# Database Connection
spring.datasource.url=${DATABASE_URL}
spring.datasource.username=${DATABASE_USERNAME}
spring.datasource.password=${DATABASE_PASSWORD}
# S3 Configuration
s3.region=${S3_REGION:eu-central-1}
s3.internal-endpoint=${S3_INTERNAL_ENDPOINT}
s3.external-endpoint=${S3_EXTERNAL_ENDPOINT}
s3.access-key=${S3_ACCESS_KEY}
s3.secret-key=${S3_SECRET_KEY}
s3.bucket=${S3_BUCKET}
# Spring Security Configuration
spring.security.oauth2.resourceserver.jwt.issuer-uri=${JWT_ISSUER_URI}
spring.security.oauth2.resourceserver.jwt.jwk-set-uri=${JWT_JWK_SET_URI}
auth.jwt.connect-timeout=${JWT_CONNECT_TIMEOUT:15s}
auth.jwt.read-timeout=${JWT_READ_TIMEOUT:20s}
