# Logging Configuration
logging.level.org.hibernate.SQL=debug
logging.level.org.hibernate.orm.jdbc.bind=trace
# JPA / Hibernate Configuration
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=false
