# Docker Compose Configuration
spring.docker.compose.file=docker-compose.yaml
spring.docker.compose.profiles.active=without-backend
# Logging Configuration
logging.level.org.hibernate.SQL=debug
logging.level.org.hibernate.orm.jdbc.bind=trace
# JPA / Hibernate Configuration
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
# PostgreSQL Configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/comics-db
spring.datasource.username=myuser
spring.datasource.password=secret
# S3 Configuration
s3.region=eu-central-1
s3.endpoint=http://localhost:9000
s3.access-key=minioadmin
s3.secret-key=minioadmin
s3.bucket=comics-bucket
# Spring Security Configuration
spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:8081/realms/comics-realm
spring.security.oauth2.resourceserver.jwt.jwk-set-uri=http://localhost:8081/realms/comics-realm/protocol/openid-connect/certs
auth.jwt.connect-timeout=15s
auth.jwt.read-timeout=20s
